### ISSUE TITLE
Unable to execute ```makemigrations``` while initializing backend server

### ISSUE THREAD

**Issue by ghost** [theindegenous-tech/Dummy_codebase#1]
````(env) PS C:\Users\Joshi\Dummy_codebase\backend> python manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\db\backends\postgresql\base.py", line 24, in <module>
    import psycopg2 as Database
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Joshi\Dummy_codebase\backend\manage.py", line 22, in <module>
    main()
  File "C:\Users\Joshi\Dummy_codebase\backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\core\management\__init__.py", line 420, in execute
    django.setup()
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\apps\config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joshi\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Joshi\Dummy_codebase\backend\users\models.py", line 2, in <module>
    from django.contrib.auth.models import AbstractUser,  BaseUserManager
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\contrib\auth\models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\contrib\auth\base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\db\models\base.py", line 141, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\db\models\base.py", line 369, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\db\models\options.py", line 235, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
                   ^^^^^^^^^^^^^^
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\utils\connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\utils\connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\db\utils.py", line 208, in create_connection
    backend = load_backend(db["ENGINE"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\db\utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joshi\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Joshi\Dummy_codebase\env\Lib\site-packages\django\db\backends\postgresql\base.py", line 28, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: DLL load failed while importing _psycopg: The specified module could not be found.`

**Comment by ghost** [comment]
While setting up the backend for the first time, I encounter the following error while making migrations on the virtual environment. I even tried commenting out the lines on views.py. Any help would be appreciated!
